# Simple Linear Regression

# importing data

dataset = read.csv('Salary_Data.csv')
#dataset = dataset[, 2:3]

# splitting the dataset into training set and test set
#install.packages('caTolls')
library(caTools)
set.seed(123)
split = sample.split(dataset$Salary, SplitRatio=2/3)
training_set = subset(dataset, split==TRUE)
test_set = subset(dataset, split==FALSE)

# feature scaling
# training_set[, 2:3] = scale(training_set[, 2:3])
# test_set[, 2:3] = scale(test_set[, 2:3])

# fitting Simple Linear Regression to the Training Set
regressor = lm(formula=Salary ~ YearsExperience,
               data=training_set)
# predicting the Test set results
y_pred = predict(regressor, newdata=test_set)

# Visualizing the Training Set Results
#install.packages('ggplot2')
library(ggplot2)
ggplot()+
  geom_point(aes(x=training_set$YearsExperience, y=training_set$Salary),
             color='red') +
  geom_line(aes(x=training_set$YearsExperience, y=predict(regressor, newdata=training_set)),
            color='blue') +
  ggtitle('Salary vs Experience (Training set)') +
  xlab('Years of Experience')
  ylab('Salary')
             
# Visualizing the Test Set Results
#install.packages('ggplot2')
library(ggplot2)
ggplot()+
  geom_point(aes(x=test_set$YearsExperience, y=test_set$Salary),
             color='red') +
  geom_line(aes(x=training_set$YearsExperience, y=predict(regressor, newdata=training_set)),
            color='blue') +
  ggtitle('Salary vs Experience (Test set)') +
  xlab('Years of Experience')
  ylab('Salary')             